// Generated by gencpp from file beginner_tutorials/my_message.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MY_MESSAGE_H
#define BEGINNER_TUTORIALS_MESSAGE_MY_MESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct my_message_
{
  typedef my_message_<ContainerAllocator> Type;

  my_message_()
    : Raimondo()
    , Morga()
    , eta(0)
    , voto(0.0)  {
    }
  my_message_(const ContainerAllocator& _alloc)
    : Raimondo(_alloc)
    , Morga(_alloc)
    , eta(0)
    , voto(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Raimondo_type;
  _Raimondo_type Raimondo;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Morga_type;
  _Morga_type Morga;

   typedef int32_t _eta_type;
  _eta_type eta;

   typedef float _voto_type;
  _voto_type voto;





  typedef boost::shared_ptr< ::beginner_tutorials::my_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::my_message_<ContainerAllocator> const> ConstPtr;

}; // struct my_message_

typedef ::beginner_tutorials::my_message_<std::allocator<void> > my_message;

typedef boost::shared_ptr< ::beginner_tutorials::my_message > my_messagePtr;
typedef boost::shared_ptr< ::beginner_tutorials::my_message const> my_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::my_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::my_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::my_message_<ContainerAllocator1> & lhs, const ::beginner_tutorials::my_message_<ContainerAllocator2> & rhs)
{
  return lhs.Raimondo == rhs.Raimondo &&
    lhs.Morga == rhs.Morga &&
    lhs.eta == rhs.eta &&
    lhs.voto == rhs.voto;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::my_message_<ContainerAllocator1> & lhs, const ::beginner_tutorials::my_message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::my_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::my_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::my_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::my_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::my_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::my_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "583fc403537dae1c9c78ff963804876f";
  }

  static const char* value(const ::beginner_tutorials::my_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x583fc403537dae1cULL;
  static const uint64_t static_value2 = 0x9c78ff963804876fULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/my_message";
  }

  static const char* value(const ::beginner_tutorials::my_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Raimondo\n"
"string Morga\n"
"int32 eta\n"
"float32 voto\n"
;
  }

  static const char* value(const ::beginner_tutorials::my_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::my_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Raimondo);
      stream.next(m.Morga);
      stream.next(m.eta);
      stream.next(m.voto);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::my_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::my_message_<ContainerAllocator>& v)
  {
    s << indent << "Raimondo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Raimondo);
    s << indent << "Morga: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Morga);
    s << indent << "eta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.eta);
    s << indent << "voto: ";
    Printer<float>::stream(s, indent + "  ", v.voto);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MY_MESSAGE_H
