controller_list:
  - name: controller_1
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - virtual_joint
      - wheel_left_joint
      - wheel_right_joint